POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "fullName": "Test User",
  "phoneNumber": "09120000000",
  "password": "password123",
  "sessions": 12,
  "planType": "Monthly"
}

### تست ورود
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "phoneNumber": "09120000000",
  "password": "password123"
}
